name: Deploy Raspberry Cluster

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  OPENVPN_DIR: openvpn

jobs:
  pre-build:
    name: Pre Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Install OpenVPN
      run: sudo apt-get install openvpn
    - name: Create .env file
      uses: ozaytsev86/create-env-file@v1
      with:
        ENV_CA_CERTIFICATE: ${{ secrets.CA_CERTIFICATE }}
    - name: test
      run: |
        ls -la
        env




    #- name: Create ca.crt from CA_CERTIFICATE secret
    #  run: |
    #    echo "${{ secrets.CA_CERTIFICATE }}" > $OPENVPN_DIR/ca.crt
    #    ls -la
    #    cd openvpn
    #    ls -la
    #    cat ca.crt

      

