name: Deploy Raspberry Cluster

on:
  pull_request:
    branches: [ "*" ]

#env:
  #OPENVPN_DIR: openvpn

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Apt Update
      run: sudo apt update
    - name: Install OpenVPN
      run: sudo apt install openvpn
    - name: Install Ansible
      run: sudo apt install ansible
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Clone renatotecchio/mikrotik_openvpn repo and create files
      run: | 
        git clone https://github.com/renatotecchio/mikrotik_openvpn.git
        cd mikrotik_openvpn
        echo "${{ secrets.CA_CERTIFICATE }}" > ca.crt
        echo "${{ secrets.CLIENT_CERTIFICATE }}" > client.crt
        echo "${{ secrets.CLIENT_PRIVATE_KEY }}" > client.key
        echo "${{ secrets.OPENVPN_CLIENT_CREDENTIAL }}" > client.auth
        sed 's/REMOTE_IP_ADDRESS/${{ secrets.REMOTE_IP_ADDRESS }}/' client_template.conf > client.conf
    - name: Connection OpenVPN
      run: |
        cd mikrotik_openvpn
        sudo openvpn --config client.conf&
    - name: Run Ansible Playbook
      run: |
        ifconfig
    
    #- name: Upload
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: ca.crt
    #    path: openvpn/ca.crt
