name: Deploy Raspberry Cluster

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  pre-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install OpenVPN
      run: sudo apt-get install openvpn
    - name: Create ca.crt from CA_CERTIFICATE secret
      run: |
        echo "${{ secrets.CA_CERTIFICATE }}" > ca.crt
        ls -la

      

