name: Deploy Raspberry Cluster

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

env:
  OPENVPN_DIR: openvpn

jobs:
  pre-build:
    name: Pre Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Create ca.crt from CA_CERTIFICATE secret
      run: echo "${{ secrets.CA_CERTIFICATE }}" > $OPENVPN_DIR/ca.crt
    - name: Create client.crt from CLIENT_CERTIFICATE secret
      run: echo "${{ secrets.CLIENT_CERTIFICATE }}" > $OPENVPN_DIR/client.crt
    - name: Create client.key from CLIENT_PRIVATE_KEY secret
      run: echo "${{ secrets.CLIENT_PRIVATE_KEY }}" > $OPENVPN_DIR/client.key
    - name: Create client.auth from OPENVPN_CLIENT_CREDENTIAL secret
      run: echo "${{ secrets.OPENVPN_CLIENT_CREDENTIAL }}" > $OPENVPN_DIR/client.auth
    - name: Install OpenVPN
      run: sudo apt-get install openvpn
    - name: Connection OpenVPN
      run: |
        cd openvpn
        sudo openvpn --config client.conf&
    - name: test
      run: |
        ifconfig
        ping 192.168.10.100
    
    #- name: Upload
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: ca.crt
    #    path: openvpn/ca.crt
