name: Deploy Raspberry Cluster

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

#env:
  #OPENVPN_DIR: openvpn

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Apt Update
      run: sudo apt update
    - name: Install OpenVPN
      run: sudo apt install openvpn
    - name: Install Ansible
      run: sudo apt install ansible
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Clone renatotecchio/mikrotik_openvpn repo
      run: | 
        git clone https://github.com/renatotecchio/mikrotik_openvpn.git
        cd mikrotik_openvpn
    - name: Create ca.crt from CA_CERTIFICATE secret
      run: echo "${{ secrets.CA_CERTIFICATE }}" > ca.crt
    - name: Create client.crt from CLIENT_CERTIFICATE secret
      run: echo "${{ secrets.CLIENT_CERTIFICATE }}" > client.crt
    - name: Create client.key from CLIENT_PRIVATE_KEY secret
      run: echo "${{ secrets.CLIENT_PRIVATE_KEY }}" > client.key
    - name: Create client.auth from OPENVPN_CLIENT_CREDENTIAL secret
      run: echo "${{ secrets.OPENVPN_CLIENT_CREDENTIAL }}" > client.auth
    - name: Replace REMOTE_IP_ADDRESS variable
      run: sed 's/REMOTE_IP_ADDRESS/${{ secrets.REMOTE_IP_ADDRESS }}/' client_template.conf > client.conf
    - name: Connection OpenVPN
      run: |
        cd openvpn
        sudo openvpn --config client.conf&
    

    - name: Run Ansible Playbook
      run: |
        ifconfig
    
    #- name: Upload
    #  uses: actions/upload-artifact@v2
    #  with:
    #    name: ca.crt
    #    path: openvpn/ca.crt
