name: Deploy Raspberry Cluster

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  pre-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install OpenVPN
      run: sudo apt-get install openvpn
    - name: Test ping
      env:
        REMOTE_IP_ADDRESS: ${{ secrets.REMOTE_IP_ADDRESS }}
      run: ping -c 5 ${{ env.REMOTE_IP_ADDRESS }}

